
## NUCLEO-F446RE

MCU ?= cortex-m4
FPU ?= fpv4-sp-d16
ISAFLAGS  = -mcpu=$(MCU) -mfpu=$(FPU) -mfloat-abi=hard -mthumb

VARIANT = NUCLEO_F446RE

HAL_SRC = STM32F4xx

ARD_CFLAGS :=
ARD_CFLAGS += -D ARDUINO=10814
ARD_CFLAGS += -D ARDUINO_ARCH_STM32
ARD_CFLAGS += -D ARDUINO_LIB_DISCOVERY_PHASE
ARD_CFLAGS += -D ARDUINO_NUCLEO_F446RE
ARD_CFLAGS += -D BOARD_NAME="NUCLEO_F446RE"
ARD_CFLAGS += -D HAL_UART_MODULE_ENABLED
ARD_CFLAGS += -D STM32F446xx
ARD_CFLAGS += -D STM32F4xx

MASS_OPTION = -O "NODE_F446RE,NUCLEO"

FLASH_SIZE=524288
RAM_SIZE=131072

## Select the serial port for your board
# MONITOR_PORT ?= /dev/ttyACM0
# MONITOR_PORT ?= /dev/ttyUSB0

# ARM_MATH_LIB = $(DISTRO)/ArduinoModule-CMSIS/CMSIS/CMSIS/Lib/GCC -larm_cortexM3l_math
# ARM_MATH_LIB = $(DISTRO)/ArduinoModule-CMSIS/CMSIS/CMSIS/Lib/GCC -larm_cortexM4lf_math

OPENOCD_INTERFACE=stlink
OPENOCD_TARGET=stm32f4x
