## BLUEPILL_F103C8

MCU ?= cortex-m3
ISAFLAGS  = -mcpu=$(MCU) -mfloat-abi=soft -mthumb

VARIANT = PILL_F103XX
# VARIANT = Generic_F103Cx
HAL_SRC = STM32F1xx

ARD_CFLAGS :=
ARD_CFLAGS += -D ARDUINO=10814
ARD_CFLAGS += -D ARDUINO_ARCH_STM32
ARD_CFLAGS += -D ARDUINO_BLUEPILL_F103C8
ARD_CFLAGS += -D ARDUINO_LIB_DISCOVERY_PHASE
ARD_CFLAGS += -D BOARD_NAME=BLUEPILL_F103C8
ARD_CFLAGS += -D HAL_UART_MODULE_ENABLED
ARD_CFLAGS += -D STM32F103xB
ARD_CFLAGS += -D STM32F1xx
MASS_OPTION = -O ""

FLASH_SIZE=65536
RAM_SIZE=20480

## Select the serial port for your board
# MONITOR_PORT ?= /dev/ttyACM0
# MONITOR_PORT ?= /dev/ttyUSB0

# ARM_MATH_LIB = $(DISTRO)/ArduinoModule-CMSIS/CMSIS/CMSIS/Lib/GCC -larm_cortexM3l_math
# ARM_MATH_LIB = $(DISTRO)/ArduinoModule-CMSIS/CMSIS/CMSIS/Lib/GCC -larm_cortexM4lf_math

OPENOCD_INTERFACE=stlink-v2
OPENOCD_TARGET=stm32f1x

